/*
module.exports = [
    {
        "model":  "beers",
        "items": [
            {"beerName": "Smuttynose Pale","beerStyle": "Pale Ale"},
            {"beerName": "St Peter's Golden Ale", "beerStyle": "Pale Ale"},
            {"beerName": "Harviestoun Bitter & Twisted", "beerStyle": "Pale Ale"},
            {"beerName": "Rising Tide Daymark", "beerStyle": "Pale Ale"},
            {"beerName": "Lakefront Pale Ale", "beerStyle": "Pale Ale"},
            {"beerName": "Coniston Blue Bird Bitter", "beerStyle": "Pale Ale"},
            {"beerName": "Ridgeway Bitter", "beerStyle": "Pale Ale"},
            {"beerName": "Ridgeway Ivanhoe", "beerStyle": "Pale Ale"},
            {"beerName": "Nogne-o Pale", "beerStyle": "Pale Ale"},
            {"beerName": "North Coast Red Seal Pale", "beerStyle": "Pale Ale"},
            {"beerName": "Anchor Steam", "beerStyle": "Pale Ale"},
            {"beerName": "Rogue Brutal Bitter", "beerStyle": "Pale Ale"},
            {"beerName": "Anchor Small Beer", "beerStyle": "Pale Ale"},
            {"beerName": "Maine Beer Company Peeper", "beerStyle": "Pale Ale"},
            {"beerName": "Dogfish Head 60 Min Ipa - Draught", "beerStyle": "IPA"},
            {"beerName": "Dogfish Head 90 Min Ipa", "beerStyle": "IPA"},
            {"beerName": "Smuttynose Ipa", "beerStyle": "IPA"},
            {"beerName": "St Peter's Ipa", "beerStyle": "IPA"},
            {"beerName": "Meantime Ipa", "beerStyle": "IPA"},
            {"beerName": "Ridgeway Ipa", "beerStyle": "IPA"},
            {"beerName": "North Coast Acme Ipa", "beerStyle": "IPA"},
            {"beerName": "Anchor Liberty", "beerStyle": "IPA"},
            {"beerName": "Victory Hop Devil Ipa", "beerStyle": "IPA"},
            {"beerName": "Cervesera Del Montseny +lupulus Iberian Ale", "beerStyle": "IPA"},
            {"beerName": "Green Flash West Coast Ipa", "beerStyle": "IPA"},
            {"beerName": "Green Flash Hop Head Red Ipa", "beerStyle": "IPA"},
            {"beerName": "Southern Tier Ipa", "beerStyle": "IPA"},
            {"beerName": "Maine Beer Company Lunch", "beerStyle": "IPA"},
            {"beerName": "Founders Centennial Ipa", "beerStyle": "IPA"},
            {"beerName": "Lagunitas Ipa", "beerStyle": "IPA"},
            {"beerName": "Dogfish Head Indian Brown Ale", "beerStyle": "Brown Ale"},
            {"beerName": "Smuttynose Old Brown Dog", "beerStyle": "Brown Ale"},
            {"beerName": "Nogne-o Brown", "beerStyle": "Brown Ale"},
            {"beerName": "Rogue Hazelnut Brown", "beerStyle": "Brown Ale"},
            {"beerName": "Rogue Dead Guy", "beerStyle": "Amber Ale"},
            {"beerName": "Porterhouse Irish Red", "beerStyle": "Amber Ale"},
            {"beerName": "Maine Beer Company Zoe", "beerStyle": "Amber Ale"},
            {"beerName": "Harviestoun Old Engine Oil", "beerStyle": "Scotch Ale"},
            {"beerName": "Williams Brothers Froach Heather Ale", "beerStyle": "Scotch Ale"},
            {"beerName": "Williams Brothers Kelpie Seaweed Ale", "beerStyle": "Scotch Ale"},
            {"beerName": "Inveralmond Black Friar", "beerStyle": "Scotch Ale"},
            {"beerName": "Meantime Scotch", "beerStyle": "Scotch Ale"},
            {"beerName": "Smuttynose Porter", "beerStyle": "Porter"},
            {"beerName": "St Peter's Porter", "beerStyle": "Porter"},
            {"beerName": "Meantime Coffee Porter", "beerStyle": "Porter"},
            {"beerName": "Bull Jagger Baltic Porter", "beerStyle": "Porter"},
            {"beerName": "Sinebrychoff Porter", "beerStyle": "Porter"},
            {"beerName": "Hambleton Nightmare Porter", "beerStyle": "Porter"},
            {"beerName": "Nogne-o Porter", "beerStyle": "Porter"},
            {"beerName": "Haand Bryggeriet Norse Porter", "beerStyle": "Porter"},
            {"beerName": "Anchor Porter", "beerStyle": "Porter"},
            {"beerName": "Rogue Mocha Porter", "beerStyle": "Porter"},
            {"beerName": "Jw Lees Manchester Star", "beerStyle": "Porter"},
            {"beerName": "Victory Baltic Thunder", "beerStyle": "Porter"},
            {"beerName": "St Peter's Cream Stout", "beerStyle": "Stout"},
            {"beerName": "Orkney Island Dragonhead Stout", "beerStyle": "Stout"},
            {"beerName": "Ridgeway Stout", "beerStyle": "Stout"},
            {"beerName": "Nogne-o Imperial Stout", "beerStyle": "Stout"},
            {"beerName": "North Coast Old Rasputin Imperial Stout", "beerStyle": "Stout"},
            {"beerName": "Sam Smith Oatmeal Stout", "beerStyle": "Stout"},
            {"beerName": "Sam Smith Imperial Stout", "beerStyle": "Stout"},
            {"beerName": "Emelisse Imperial Russian Stout", "beerStyle": "Stout"},
            {"beerName": "Rogue Shakespeare Stout", "beerStyle": "Stout"},
            {"beerName": "Dieu Du Ciel Peche Mortel", "beerStyle": "Stout"},
            {"beerName": "High & Mighty Two Headed Beast", "beerStyle": "Stout"},
            {"beerName": "Hook Norton Double Stout", "beerStyle": "Stout"},
            {"beerName": "Victory Storm King Imperial Stout", "beerStyle": "Stout"},
            {"beerName": "Porterhouse Xxxx Full Stout", "beerStyle": "Stout"},
            {"beerName": "Porterhouse Oyster Stout", "beerStyle": "Stout"},
            {"beerName": "Monetgioco Demon Hunter", "beerStyle": "Barleywine"},
            {"beerName": "Anchor Old Foghorn", "beerStyle": "Barleywine"},
            {"beerName": "North Coast Old Stock", "beerStyle": "Barleywine"},
            {"beerName": "De Halve Maan Brugse Zot", "beerStyle": "Belgian Blonde"},
            {"beerName": "Dupont Moinette Blonde", "beerStyle": "Belgian Blonde"},
            {"beerName": "De Ranke Guldenberg", "beerStyle": "Belgian Blonde"},
            {"beerName": "Ellezelloise Quintine Blonde", "beerStyle": "Belgian Blonde"},
            {"beerName": "Kerkom Bink Blonde", "beerStyle": "Belgian Blonde"},
            {"beerName": "Caracole Saxo", "beerStyle": "Belgian Blonde"},
            {"beerName": "De La Senne Zinnebir", "beerStyle": "Belgian Blonde"},
            {"beerName": "Hof Ten Dormaal Blonde", "beerStyle": "Belgian Blonde"},
            {"beerName": "Thiriez Blonde", "beerStyle": "Belgian Blonde"},
            {"beerName": "De Ranke Xx Bitter", "beerStyle": "Belgian IPA"},
            {"beerName": "De La Senne Taras Boulba", "beerStyle": "Belgian IPA"},
            {"beerName": "Thiriez Xtra", "beerStyle": "Belgian IPA"},
            {"beerName": "Picobrouwerij Alvinne Extra", "beerStyle": "Belgian IPA"},
            {"beerName": "Het Anker Gouden Carolus Hopsinjoor", "beerStyle": "Belgian IPA"},
            {"beerName": "Urthel Hop-it", "beerStyle": "Belgian IPA"},
            {"beerName": "Scheldebrouwerij Hop Ruiter", "beerStyle": "Belgian IPA"},
            {"beerName": "Bosteels Kwak", "beerStyle": "Belgian Amber"},
            {"beerName": "Caracole", "beerStyle": "Belgian Amber"},
            {"beerName": "Hof Ten Dormaal Amber", "beerStyle": "Belgian Amber"},
            {"beerName": "Thiriez Amber", "beerStyle": "Belgian Amber"},
            {"beerName": "Unibroue Blanche De Chanmbly - Daught", "beerStyle": "Witbier"},
            {"beerName": "Unibroue Don De Dieu", "beerStyle": "Witbier"},
            {"beerName": "Caracole Troublette", "beerStyle": "Witbier"},
            {"beerName": "Ellezelloise Saisis Blanche", "beerStyle": "Witbier"},
            {"beerName": "Dieu De Ciel Rose De Hibuscus", "beerStyle": "Witbier"},
            {"beerName": "Regenboog Vuuve", "beerStyle": "Witbier"},
            {"beerName": "Dupont Saison", "beerStyle": "Saison"},
            {"beerName": "Dupont Biere Du Miel", "beerStyle": "Saison"},
            {"beerName": "Dupont Foret", "beerStyle": "Saison"},
            {"beerName": "St Amand Biere De Garde", "beerStyle": "Saison"},
            {"beerName": "Castelain Biere De Garde", "beerStyle": "Saison"},
            {"beerName": "La Choulette Framboise", "beerStyle": "Saison"},
            {"beerName": "Theillier La Bavaisienne", "beerStyle": "Saison"},
            {"beerName": "Oxbow Farmhouse Pale", "beerStyle": "Saison"},
            {"beerName": "Stillwater Stateside", "beerStyle": "Saison"},
            {"beerName": "Jandrain-jandrenouille Iv V or Vi", "beerStyle": "Saison"},
            {"beerName": "Unibroue Maudite", "beerStyle": "Dubbel"},
            {"beerName": "Caracole Nostradamus", "beerStyle": "Dubbel"},
            {"beerName": "Kerkom Bink Bruin", "beerStyle": "Dubbel"},
            {"beerName": "St Bernardus Prior 8", "beerStyle": "Dubbel"},
            {"beerName": "North Coast Brother Thelonious", "beerStyle": "Dubbel"},
            {"beerName": "Brooklyn Local 2", "beerStyle": "Dubbel"},
            {"beerName": "Augustijn Tripel", "beerStyle": "Tripel"},
            {"beerName": "Unibroue La Fin Du Monde", "beerStyle": "Tripel"},
            {"beerName": "De Proef Slaapmutske Tripel Nightcap", "beerStyle": "Tripel"},
            {"beerName": "Kerkom Bink Tripel", "beerStyle": "Tripel"},
            {"beerName": "Bosteels Tripel Karmeliet", "beerStyle": "Tripel"},
            {"beerName": "St Bernardus Tripel", "beerStyle": "Tripel"},
            {"beerName": "Val Dieu Tripel", "beerStyle": "Tripel"},
            {"beerName": "Allagash Tripel", "beerStyle": "Tripel"},
            {"beerName": "Brooklyn Local 1", "beerStyle": "Tripel"},
            {"beerName": "La Rulles Trippel", "beerStyle": "Tripel"},
            {"beerName": "Off List Draught Choice", "beerStyle": "Tripel"},
            {"beerName": "Cask - Choice", "beerStyle": "Tripel"},
            {"beerName": "Cask - Choice2", "beerStyle": "Tripel"},
            {"beerName": "Three Musketeers Troubador Obscura", "beerStyle": "Belgian Stout"},
            {"beerName": "Ellezelloise Hercule Stout", "beerStyle": "Belgian Stout"},
            {"beerName": "Pater Lieven Buffalo Stout", "beerStyle": "Belgian Stout"},
            {"beerName": "Picobrouwerij Alvinne Podge Imperial Stout", "beerStyle": "Belgian Stout"},
            {"beerName": "Unibroue Chambly Noir", "beerStyle": "Belgian Stout"},
            {"beerName": "De La Senne Stouterik", "beerStyle": "Belgian Stout"},
            {"beerName": "Allagash Black", "beerStyle": "Belgian Stout"},
            {"beerName": "De Ranke Noir De Dottignies", "beerStyle": "Belgian Stout"},
            {"beerName": "De Dolle Extra Export Stout", "beerStyle": "Belgian Stout"},
            {"beerName": "Dubuisson Bush Scaldis", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Unibroue Trois Pistoles", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Unibroue La Terrible", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Gouden Carolus Cuvee", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "St Bernardus Abt 12", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Val Dieu Grand Cru", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Urthel Samaranth Quadrium 12", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Allagash Four", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "De Proef Lozen Boer Abt", "beerStyle": "Belgian Strong Ale"},
            {"beerName": "Achel Blonde", "beerStyle": "Trappist Ale"},
            {"beerName": "Achel Bruin", "beerStyle": "Trappist Ale"},
            {"beerName": "Koningshoeven Dubbel", "beerStyle": "Trappist Ale"},
            {"beerName": "Koningshoeven Trippel", "beerStyle": "Trappist Ale"},
            {"beerName": "Koningshoeven Quadrupel", "beerStyle": "Trappist Ale"},
            {"beerName": "Chimay Red Premier", "beerStyle": "Trappist Ale"},
            {"beerName": "Chimay White Cinq Cents", "beerStyle": "Trappist Ale"},
            {"beerName": "Chimay Blue Grand Reserve", "beerStyle": "Trappist Ale"},
            {"beerName": "Orval", "beerStyle": "Trappist Ale"},
            {"beerName": "Rochefort 6", "beerStyle": "Trappist Ale"},
            {"beerName": "Rochefort 8", "beerStyle": "Trappist Ale"},
            {"beerName": "Rochefort 10", "beerStyle": "Trappist Ale"},
            {"beerName": "Westmalle Dubbel", "beerStyle": "Trappist Ale"},
            {"beerName": "Westmalle Tripel", "beerStyle": "Trappist Ale"},
            {"beerName": "Jolly Pumpkin Oro De Calabaza", "beerStyle": "Sour / Wild"},
            {"beerName": "De Proef Reinaert Flemish Wild Ale", "beerStyle": "Sour / Wild"},
            {"beerName": "De Ranke Kriek", "beerStyle": "Sour / Wild"},
            {"beerName": "De Ranke Cuvee", "beerStyle": "Sour / Wild"},
            {"beerName": "Petrus Oud Bruin", "beerStyle": "Flemish Brown"},
            {"beerName": "Panil Barriquee", "beerStyle": "Flemish Brown"},
            {"beerName": "Jolly Pumpkin La Roja", "beerStyle": "Flemish Brown"},
            {"beerName": "De Proef Zoetzuur Flemish Ale", "beerStyle": "Flemish Brown"},
            {"beerName": "Cantillon Gueuze", "beerStyle": "Lambic"},
            {"beerName": "Cantillon Kriek", "beerStyle": "Lambic"},
            {"beerName": "Tilquin Oude Gueze", "beerStyle": "Lambic"},
            {"beerName": "Drie Fonteinen Oude Geuze", "beerStyle": "Lambic"},
            {"beerName": "Drie Fonteinen Oude Kriek", "beerStyle": "Lambic"},
            {"beerName": "Hannsens Oude Gueuze", "beerStyle": "Lambic"},
            {"beerName": "Hannsens Oude Kriek", "beerStyle": "Lambic"},
            {"beerName": "Hannsens Oudbeitje", "beerStyle": "Lambic"},
            {"beerName": "Schlenkerla Helles", "beerStyle": "Lager"},
            {"beerName": "Monchshof Kellerbrau", "beerStyle": "Lager"},
            {"beerName": "Sapporo", "beerStyle": "Lager"},
            {"beerName": "Christoffel Bier Blonde", "beerStyle": "Lager"},
            {"beerName": "Bull Jagger Portland Lager", "beerStyle": "Lager"},
            {"beerName": "Klosterbrauerei Ettal Edel Hell", "beerStyle": "Lager"},
            {"beerName": "Kulmbacher Pils", "beerStyle": "Pilsner"},
            {"beerName": "Bull Jagger Big Claw Pilsner", "beerStyle": "Pilsner"},
            {"beerName": "North Coast Scrimshaw Pilsner", "beerStyle": "Pilsner"},
            {"beerName": "Victory Prima Pils", "beerStyle": "Pilsner"},
            {"beerName": "Schlenkerla Maerzen", "beerStyle": "Rauchbier"},
            {"beerName": "Schlenkerla Urbock", "beerStyle": "Rauchbier"},
            {"beerName": "Schlenkerla Weizen", "beerStyle": "Rauchbier"},
            {"beerName": "Spezial Rauchbier Lager", "beerStyle": "Rauchbier"},
            {"beerName": "Reissdorf Kolsch", "beerStyle": "Kolsch"},
            {"beerName": "Sunner Kolsch", "beerStyle": "Kolsch"},
            {"beerName": "High & Mighty Beer of the Gods", "beerStyle": "Kolsch"},
            {"beerName": "Lover Beer - Choice", "beerStyle": "Kolsch"},
            {"beerName": "Uerige Alt", "beerStyle": "Altbier"},
            {"beerName": "Uerige Sticke", "beerStyle": "Altbier"},
            {"beerName": "Uerige Doppelsticke", "beerStyle": "Altbier"},
            {"beerName": "Einbecker Mai Urbock", "beerStyle": "Bock"},
            {"beerName": "Kulmbacher Eku 28", "beerStyle": "Bock"},
            {"beerName": "Kulmbacher Eisbock", "beerStyle": "Bock"},
            {"beerName": "Christoffel Bok", "beerStyle": "Bock"},
            {"beerName": "Ayinger Celebrator Doppelbock", "beerStyle": "Bock"},
            {"beerName": "Einbecker Schwarzbier", "beerStyle": "Schwarzbier"},
            {"beerName": "Monchshof Schwarzbier", "beerStyle": "Schwarzbier"},
            {"beerName": "Schneider Weisse", "beerStyle": "Weisse"},
            {"beerName": "Schneider Edel Weisse", "beerStyle": "Weisse"},
            {"beerName": "Kulmbacher Kapuziner Weisse", "beerStyle": "Weisse"},
            {"beerName": "Kulmbacher Kapuziner Schwarzweisse", "beerStyle": "Weisse"},
            {"beerName": "Ayinger Ur-weisse", "beerStyle": "Weisse"},
            {"beerName": "Ayinger Brau-weisse", "beerStyle": "Weisse"},
            {"beerName": "Plank Heller Weizenbock", "beerStyle": "Weisse"},
            {"beerName": "Schneider Aventinus", "beerStyle": "Weisse"},
            {"beerName": "Schneider Eisbock", "beerStyle": "Weisse"},
            {"beerName": "Bayerischer Bahnhof Leipziger Gose", "beerStyle": "Weisse"},
            {"beerName": "Dogfish Head - Choice", "beerStyle": "Other"},
            {"beerName": "Maine Beer Company - Choice", "beerStyle": "Other"},
            {"beerName": "Dogfish Head Midas Touch", "beerStyle": "Other"},
            {"beerName": "Dogfish Head Raison D'etre", "beerStyle": "Other"},
            {"beerName": "Dogfish Head Palo Santo", "beerStyle": "Other"},
            {"beerName": "Castle Eggenberg Samiclaus Vintage", "beerStyle": "Other"},
            {"beerName": "Castle Eggenberg Samiclaus Helles", "beerStyle": "Other"},
            {"beerName": "Haand Bryggeriet Dark Force", "beerStyle": "Other"},
            {"beerName": "De Struise - Choice", "beerStyle": "Other"},
            {"beerName": "Dieu Du Ciel Route Des Epices", "beerStyle": "Other"},
            {"beerName": "Unibroue - Choice", "beerStyle": "Other"},
            {"beerName": "Jw Lees - Barrel Aged Choice", "beerStyle": "Other"},
            {"beerName": "Allagash - Choice", "beerStyle": "Other"},
            {"beerName": "De Dolle - Choice", "beerStyle": "Other"},
            {"beerName": "Staff Choice", "beerStyle": "Other"},
            {"beerName": "Staff Choice2", "beerStyle": "Other"},
        ]
    },
    {
        "model":  "lists",
        "items": [
            {
                {}
            },
        ]
    }
];//*/